# Generated by Django 4.1 on 2025-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_alter_crawlscheduling_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
