# Generated by Django 4.1 on 2025-10-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0031_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_crawl_new_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
