# Generated by Django 4.1 on 2025-12-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_formatter'),
        ('agency', '0032_page_last_crawl_new_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='formatter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='ai.formatter'),
        ),
    ]
