# Generated by Django 4.1 on 2025-11-01 18:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Model identifier (e.g., gpt-3.5-turbo)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name (e.g., GPT-3.5 Turbo)', max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], default='openai', max_length=50)),
                ('input_token_price', models.DecimalField(decimal_places=6, default=Decimal('0.0000'), help_text='Price per 1K input tokens', max_digits=10)),
                ('output_token_price', models.DecimalField(decimal_places=6, default=Decimal('0.0000'), help_text='Price per 1K output tokens', max_digits=10)),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum context length')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for use')),
                ('description', models.TextField(blank=True, help_text='Model description and capabilities', null=True)),
                ('version', models.CharField(blank=True, help_text='Model version', max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, help_text='When this model was released', null=True)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('usage_type', models.CharField(choices=[('Message Formatting', 'Message Formatting')], max_length=30)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('input_cost', models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=10)),
                ('output_cost', models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=10)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.llmmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
